-- 세이프리스 FastAPI 서버 전용 저장소
-- 비밀 키는 SQL에 넣지 않습니다. FastAPI 서버의 .env에서만 관리합니다.

create table if not exists public.safelease_users (
    id bigint generated by default as identity primary key,
    username text not null,
    username_key text not null unique,
    password_hash text not null,
    password_salt text not null,
    password_iterations integer not null check (password_iterations >= 100000),
    created_at timestamptz not null default now()
);

create table if not exists public.safelease_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.safelease_users(id) on delete cascade,
    token_hash text not null unique,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null
);

create index if not exists safelease_sessions_expires_idx
    on public.safelease_sessions(expires_at);

create table if not exists public.safelease_checklists (
    user_id bigint primary key references public.safelease_users(id) on delete cascade,
    state_json jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now(),
    constraint safelease_checklists_state_is_object
        check (jsonb_typeof(state_json) = 'object')
);

alter table public.safelease_users enable row level security;
alter table public.safelease_sessions enable row level security;
alter table public.safelease_checklists enable row level security;

-- 브라우저용 공개 키로 계정·세션·체크리스트를 직접 읽지 못하게 차단합니다.
revoke all on table public.safelease_users from anon, authenticated;
revoke all on table public.safelease_sessions from anon, authenticated;
revoke all on table public.safelease_checklists from anon, authenticated;

-- 서버의 Supabase Secret Key는 service_role로 동작합니다.
grant all on table public.safelease_users to service_role;
grant all on table public.safelease_sessions to service_role;
grant all on table public.safelease_checklists to service_role;
grant usage, select on all sequences in schema public to service_role;
